### ISSUE TITLE
Error: The terraform-provider-uptimerobot plugin crashed!

### ISSUE THREAD

**Issue by cuttingedge1109** [louy/terraform-provider-uptimerobot#117]
I am facing this error sometimes during `terraform plan`.
```
Stack trace from the terraform-provider-uptimerobot plugin:

panic: interface conversion: interface {} is nil, not float64

goroutine 71 [running]:
github.com/louy/terraform-provider-uptimerobot/uptimerobot/api.UptimeRobotApiClient.GetMonitor(0xc00003a0d4, 0x21, 0x2f222c5b, 0x2f222c5b, 0xc0004ba210, 0xc, 0xc000034600, 0x1f, 0xfba1c2, 0x4, ...)
github.com/louy/terraform-provider-uptimerobot/uptimerobot/api/monitor.go:157 +0x13a7
github.com/louy/terraform-provider-uptimerobot/uptimerobot.resourceMonitorRead(0xc000290850, 0xf814c0, 0xc000030f50, 0xc000290850, 0x0)
github.com/louy/terraform-provider-uptimerobot/uptimerobot/resource_uptimerobot_monitor.go:176 +0xd0
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0000fac00, 0xc0000807d0, 0xf814c0, 0xc000030f50, 0xc00000e338, 0x0, 0x0)
github.com/hashicorp/terraform-plugin-sdk@v1.0.0/helper/schema/resource.go:455 +0x119
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00009ea58, 0x11f6020, 0xc00065c150, 0xc000080690, 0xc00009ea58, 0xc00065c150, 0xc00008fa48)
github.com/hashicorp/terraform-plugin-sdk@v1.0.0/internal/helper/plugin/grpc_provider.go:525 +0x3d8
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0xf7ffc0, 0xc00009ea58, 0x11f6020, 0xc00065c150, 0xc00006e3c0, 0x0, 0x11f6020, 0xc00065c150, 0xc0006d8000, 0x184)
github.com/hashicorp/terraform-plugin-sdk@v1.0.0/internal/tfplugin5/tfplugin5.pb.go:3153 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000c8000, 0x1200540, 0xc0000a2d80, 0xc0005c0200, 0xc0001162d0, 0x18d5a70, 0x0, 0x0, 0x0)
google.golang.org/grpc@v1.23.0/server.go:995 +0x460
google.golang.org/grpc.(*Server).handleStream(0xc0000c8000, 0x1200540, 0xc0000a2d80, 0xc0005c0200, 0x0)
google.golang.org/grpc@v1.23.0/server.go:1275 +0xd3d
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000098480, 0xc0000c8000, 0x1200540, 0xc0000a2d80, 0xc0005c0200)
google.golang.org/grpc@v1.23.0/server.go:710 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.23.0/server.go:708 +0xa1

Error: The terraform-provider-uptimerobot plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```
Can you check this please?
Thanks.

**Comment by cuttingedge1109** [comment]
@louy any idea on this issue?
This provider doesn't work anymore.
